import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "../components/navigation/navbar/page"
import Sidebar from "../components/navigation/sidebar/page"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gallery Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className='flex'>
        <Sidebar/>
        <div className='w-full px-8 pt-12'>{children}</div>
        </div>
      </body>
    </html>
  )
}
